---
title: "Gov 50 Final Project"
author: "Lulu August"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



# Introduction


# Data Description

##### Data Wrangling

```{r loading packages}
library(foreign)
library(tidyverse)
library(broom)
```

```{r data wrangling}
lgbt <- read.spss("pew2013lgbtpublicdatarelease.sav", to.data.frame=TRUE)

lgbt_data <- lgbt |>
  select(NEWCASEID, OFTVOTE, Q53, SEX, Q71, EMPLOY2, PPEDUCAT) |>
  rename(id = NEWCASEID,
         oft_vote = OFTVOTE,
         national_acceptance = Q53,
         sex = SEX,
         local_acceptance = Q71,
         job_status = EMPLOY2,
         ed_status = PPEDUCAT) |>
  mutate(national_acceptance_mod = case_when(
    national_acceptance == "None at all" ~ 0,
    national_acceptance == "Only a little" ~ 1,
    national_acceptance == "Some" ~ 2,
    national_acceptance == "A lot" ~ 3
  )) |>
  mutate(oft_vote_mod = case_when(
    oft_vote == "Seldom" ~ 0,
    oft_vote == "Part of the time" ~ 1,
    oft_vote == "Nearly always" ~ 2,
    oft_vote == "Always" ~ 3
  )) |>
  mutate(sex_mod = if_else(sex == "Female", 1, 0)
  ) |>
  mutate(ed_status_mod = if_else(ed_status == "Bachelor's degree or higher", 1, 0)
    ) |>
  mutate(local_acceptance_mod = case_when(
    local_acceptance == "None at all" ~ 0,
    local_acceptance == "Only a little" ~ 1,
    local_acceptance == "Some" ~ 2,
    local_acceptance == "A lot" ~ 3
  )) |>
  mutate(job_status_mod = if_else(job_status == "Employed full-time", 1, 0)
  ) |>
  select(id, national_acceptance_mod, oft_vote_mod, sex_mod, ed_status_mod, local_acceptance_mod) |>
  drop_na()
head(lgbt_data)

lgbt_data |>
  filter(oft_vote_mod == 0)

lgbt_data |>
  filter(oft_vote_mod == 1)

lgbt_data |>
  filter(oft_vote_mod == 2)

lgbt_data |>
  filter(oft_vote_mod == 3)
```

##### Barplot of Dependent Variable
```{r barplot of dependent variable}
ggplot(data = lgbt_data, mapping = aes(x = factor(oft_vote_mod))) +
  geom_bar() +
  labs (x = "Number of People in Different Voting Likelihoods",
        y = "Number of People",
        title = "Voting Likelihood")
```

# Results

##### Boxplot of Main Relationship of Interest
```{r boxplot of independent and dependent variable}
ggplot(data = lgbt_data, mapping = aes(x = factor(national_acceptance_mod),
                                       y = oft_vote_mod)) +
  geom_boxplot() +
  labs(
    x = "Feelings of National Acceptance of LGBT Identity")
```

##### One Variable Linear Regression
```{r one variable linear regression}
regression <- lm(oft_vote_mod ~ national_acceptance_mod, data = lgbt_data)
tidy(regression) |>
  knitr::kable(digits = 3, caption = "Multiple Variable Regression of Different Factors and Voting Likelihood")
```

##### Multiple Variable Regression
```{r multiple variable linear regression}
multi_regression <- lm(oft_vote_mod ~ national_acceptance_mod + sex_mod + ed_status_mod + local_acceptance_mod, data = lgbt_data)
tidy(multi_regression) |>
  knitr::kable(digits = 3, caption = "Multiple Variable Regression of Different Factors and Voting Likelihood")
```


# Conclusion
